source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Aurum_Example', :exclusive => true do
  pod "Aurum", :path => "../"
end

target 'Aurum_Tests', :exclusive => true do
  pod "Aurum", :path => "../"

  pod 'Quick', :git => 'https://github.com/Quick/Quick.git'
  pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git'
end
